version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mkn0021
      POSTGRES_PASSWORD: admin1991
      POSTGRES_DB: bistro92
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"    # Message broker
      - "15672:15672"  # RabbitMQ management UI

  api:
    image: mkn0021/bistro92-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://mkn0021:admin1991@postgres:5432/bistro92
      - API_KEY=835cf0faa598693992deb0cdd41f1142164a4f1b9f9014ba7fd4af4e8d9fa1d9
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq

volumes:
  postgres_data:
